### PR TITLE
feat: add support for Retina displays

### LINKED ISSUE #662: adapt WebGL canvas resolution to Hi-dpi screens
We should use the window.devicePixelRatio to set the canvas width and height. 
use width=height=100% to keep the canvas size fitting to its parent.

Note: we need to test this on a few monitors. I have a monitor which gives a devicePixelRatio  of 0.75, which means lower resolution. we should check to see if it helps in this case.

### PR DESCRIPTION
**Pull request by mauroporras**
Close #662

### CODE REVIEW

**Comment by mauroporras** [comment]
Example of a rendered asset:

Screen Shot 2022-02-02 at 11 56 12

**Comment by phtaylor** [comment]
image

The new test results raise some questions:
 - why the canvas did not fill the available space before. 
      - it seems that the width and height value of the parent did not cause the canvas to fit the parent. However 100% width and height works. 
 - Does the Percy testing renderer have a device pixel ratio < 1 ?
 - Why are the new screenshots distorted? The width and height values returned by the parent element are not exactly regular. 
     - Could this occur on a client machine?

My feeling is that we should merge this PR and create an issue to investigate the Percy screenshot distortion and device pixel ratio.
The canvas not filling the available space should have been a cause for concern before, so its swapping one issue for another.

**Comment by mauroporras** [comment]
> we should merge this PR and create an issue to investigate the Percy screenshot distortion and device pixel ratio.

But in doing so, don't we take the risk of braking the tests on `main` at some point?
My suggestion is to try and fix it in this PR. I've isolated a single spec, the sphere one.

**Comment by phtaylor** [comment]
We should check that the box size we get is not already multiplied by the device pixel ratio.
```
    try {
      // only call us of the number of device pixels changed
      // @ts-ignore
      resizeObserver.observe(this.__glcanvas.parentNode, { box: 'device-pixel-content-box' })
    } catch (ex) {
      // device-pixel-content-box is not supported so fallback to this
      // @ts-ignore
      resizeObserver.observe(this.__glcanvas.parentNode, { box: 'content-box' })
    }
 ``

**Comment by phtaylor** [comment]
if the values provided in the contentRect are already 'device pixels', then we shouldn't then multiply  devicePixelRatio

```
        const displayWidth = Math.round(entry.contentRect.width)
        const displayHeight = Math.round(entry.contentRect.height)
```

What we need to know. 
Try the resuize observer with both a regular listener. 
```
resizeObserver.observe(this.__glcanvas.parentNode, { box: 'content-box' })
```

and then again with the device pixel ration version
```
resizeObserver.observe(this.__glcanvas.parentNode, { box: 'device-pixel-content-box' })
```

if they are different (they should be), and if the second one gives us the same as the values as the first * devicePixelRatios.
then we know we already have device pixels, and should not multiply again. 


What I think we should do:
1. Remove the new multiply by devicePixelRatio.
2. Keep the canvas sizing to fit its parent using 100% width and height.
3. We should divide the resolution of the occlusion buffer by device pixel ratios.
    The occlusion buffer resolution has a big impact on occlusion culling performance. 
    Check the 'occlusion-culling' test. 
 4. Add a 'superResolution' number value to the renderer that users can set. It should default to 1.
   This allows users to force rendering at a higher resolution than the screen. The canvas display will then resize it to fit the actual.

**Pull request closed without merging**
